on: push
name: "âœï¸ Generate changelog"
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: ğŸ• Clone and checkout of the actual branch
              uses: actions/checkout@v2
            - name: "âœï¸ Generate changelog"
              id: generate-changelog
              uses: heinrichreimer/action-github-changelog-generator@v2.1
              with:
                token: ${{ secrets.CHANGELOG}}
                author: "false"
